FROM ghcr.io/openccu/openccu:latest

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        wget \
        ca-certificates \
        build-essential \
        bison \
        flex \
        libssl-dev \
        gpg \
    && rm -rf /var/lib/apt/lists/*